// Datos iniciales de tu ministerio (se cargan solo la primera vez)
export const SEED_STUDENTS = [
  { id: 1, name: "Miguel Eduardo Parada", phone: "(562) 668-1311", ffg: "Dominick", age: "29", coach: "Alex Gonzalez", active: true, steps: {}, attendance: {} },
  { id: 2, name: "Joe Samayoa", phone: "(213) 801-2957", ffg: "Bobby Arzola", age: "", coach: "Alex Gonzalez", active: true, steps: {}, attendance: {} },
  { id: 3, name: "Johnny Carreon", phone: "(562) 739-7561", ffg: "Isaac Martinez", age: "31", coach: "Alex Gonzalez", active: true, steps: {}, attendance: {} },
  { id: 4, name: "Daniel Castaneda", phone: "3237703762", ffg: "edgar medallo", age: "", coach: "Alex Gonzalez", active: true, steps: {}, attendance: {} },
  { id: 5, name: "Oscar Cuevas", phone: "6263437319", ffg: "dylane", age: "", coach: "Alex Gonzalez", active: true, steps: {}, attendance: {} },
  { id: 6, name: "Jonathan Juarez", phone: "(562) 623-8372", ffg: "Chris Perez", age: "29", coach: "Alex Gonzalez", active: true, steps: {}, attendance: {} },
  { id: 7, name: "Arturo Pineda Duarte", phone: "4242967432", ffg: "isaac Martinez", age: "", coach: "Alex Gonzalez", active: true, steps: {}, attendance: {} },
  { id: 8, name: "Sebastiian Jiminez", phone: "5626461094", ffg: "isaac Martinez", age: "", coach: "Alex Gonzalez", active: true, steps: {}, attendance: {} },
  { id: 9, name: "Anthony V", phone: "(562) 280-8408", ffg: "Alfred Appel", age: "30", coach: "Alfred Appel", active: true, steps: {}, attendance: {} },
  { id: 10, name: "Steven Sotelo", phone: "(626) 624-7070", ffg: "Will Biscardi", age: "27", coach: "Alfred Appel", active: true, steps: {}, attendance: {} },
  { id: 11, name: "James Arredondo", phone: "(626) 566-5690", ffg: "Christian Luna", age: "31", coach: "Alfred Appel", active: true, steps: {}, attendance: {} },
  { id: 12, name: "Jose Araujo", phone: "(562) 229-4751", ffg: "Alfred Appel", age: "", coach: "Alfred Appel", active: true, steps: {}, attendance: {} },
  { id: 13, name: "Jaron Ross", phone: "(562) 254-5777", ffg: "Isaac Martinez", age: "23", coach: "Alfred Appel", active: true, steps: {}, attendance: {} },
  { id: 14, name: "John Talski", phone: "5628191862", ffg: "Davon Livingston", age: "45", coach: "Alfred Appel", active: true, steps: {}, attendance: {} },
  { id: 15, name: "Ruben Salazar", phone: "(626) 472-4144", ffg: "Ruben Salazar", age: "53", coach: "Alfred Appel", active: true, steps: {}, attendance: {} },
  { id: 16, name: "Jairo", phone: "5625195006", ffg: "rafael ortiz", age: "", coach: "Alfred Appel", active: true, steps: {}, attendance: {} },
  { id: 17, name: "Joshua Avila", phone: "(323) 477-6856", ffg: "Ruben Salazar", age: "", coach: "Chris Perez", active: true, steps: {}, attendance: {} },
  { id: 18, name: "Carlos Lucas", phone: "(562) 359-6693", ffg: "Mel Dylane", age: "19", coach: "Chris Perez", active: true, steps: {}, attendance: {} },
  { id: 19, name: "Khalil", phone: "318-376-2451", ffg: "", age: "", coach: "Chris Perez", active: true, steps: {}, attendance: {} },
  { id: 20, name: "Jojo Eljaik", phone: "(562) 332-9647", ffg: "Will Biscardi", age: "19", coach: "Chris Perez", active: true, steps: {}, attendance: {} },
  { id: 21, name: "Jeff Phan", phone: "(626) 803-7054", ffg: "Christian Luna", age: "22", coach: "Chris Perez", active: true, steps: {}, attendance: {} },
  { id: 22, name: "Jose Urbina", phone: "(562) 440-0145", ffg: "Chris Perez", age: "19", coach: "Chris Perez", active: true, steps: {}, attendance: {} },
  { id: 23, name: "Brandon Garcia", phone: "(714) 342-7512", ffg: "Herbert Solorzano", age: "", coach: "Chris Perez", active: true, steps: {}, attendance: {} },
  { id: 24, name: "Armando Guadalupe", phone: "7149246307", ffg: "edgar medallo", age: "", coach: "Chris Perez", active: true, steps: {}, attendance: {} },
  { id: 25, name: "Francisco Lopez", phone: "2137562757", ffg: "rafa ortiz", age: "", coach: "Chris Perez", active: true, steps: {}, attendance: {} },
  { id: 26, name: "Jeremy De Fiesta", phone: "(626) 547-1874", ffg: "Bobby Arzola", age: "16", coach: "Dylane Kamgang", active: true, steps: {}, attendance: {} },
  { id: 27, name: "Robert Gonsalez", phone: "(909) 312-9101", ffg: "Bobby Arzola", age: "16", coach: "Dylane Kamgang", active: true, steps: {}, attendance: {} },
  { id: 28, name: "Damian Ramirez", phone: "(323) 541-3352", ffg: "Christian Luna", age: "15", coach: "Dylane Kamgang", active: true, steps: {}, attendance: {} },
  { id: 29, name: "Anthony Workman", phone: "(909) 581-0957", ffg: "Mel Dylane", age: "16", coach: "Dylane Kamgang", active: true, steps: {}, attendance: {} },
  { id: 30, name: "Logan", phone: "(562) 556-8265", ffg: "Chris Perez", age: "16", coach: "Dylane Kamgang", active: true, steps: {}, attendance: {} },
  { id: 31, name: "Jhosep", phone: "5623506737", ffg: "Chris Perez", age: "", coach: "Dylane Kamgang", active: true, steps: {}, attendance: {} },
  { id: 32, name: "Daniel Ramirez", phone: "5629394504", ffg: "Chris Perez", age: "", coach: "Dylane Kamgang", active: true, steps: {}, attendance: {} },
  { id: 33, name: "John Mclean", phone: "9092586250", ffg: "Mel Dylane", age: "15", coach: "Evan Garcia", active: true, steps: {}, attendance: {} },
  { id: 34, name: "Jaden Amateo", phone: "(562) 939-0118", ffg: "Evan Garcia", age: "17", coach: "Evan Garcia", active: true, steps: {}, attendance: {} },
  { id: 35, name: "Jake Ward", phone: "(562) 338-1064", ffg: "Evan Garcia", age: "16", coach: "Evan Garcia", active: true, steps: {}, attendance: {} },
  { id: 36, name: "Joseph Bello", phone: "5623506737", ffg: "Chris Perez", age: "", coach: "Evan Garcia", active: true, steps: {}, attendance: {} },
  { id: 37, name: "Ricky Telles", phone: "(562) 631-9490", ffg: "Dylan", age: "", coach: "Evan Garcia", active: true, steps: {}, attendance: {} },
  { id: 38, name: "Simon Pantoja", phone: "(323) 209-7704", ffg: "Yony Bautista", age: "14", coach: "Yony Bautista", active: true, steps: {}, attendance: {} },
  { id: 39, name: "Andrew Velascos", phone: "9093446108", ffg: "chris perez", age: "16", coach: "Yony Bautista", active: true, steps: {}, attendance: {} },
  { id: 40, name: "Victor Aquino", phone: "5623743311", ffg: "chris perez", age: "", coach: "Yony Bautista", active: true, steps: {}, attendance: {} },
  { id: 41, name: "Danie", phone: "", ffg: "", age: "", coach: "Yony Bautista", active: true, steps: {}, attendance: {} },
  { id: 42, name: "Jose Luis", phone: "(714) 474-3371", ffg: "Chris Perez", age: "29", coach: "Cesar Lopez", active: true, steps: {}, attendance: {} },
  { id: 43, name: "Esteban Arias", phone: "(562) 536-4330", ffg: "Isaac Martinez", age: "33", coach: "Cesar Lopez", active: true, steps: {}, attendance: {} },
  { id: 44, name: "Eduardo Toscano", phone: "2138277418", ffg: "edgar mellado", age: "", coach: "Cesar Lopez", active: true, steps: {}, attendance: {} },
  { id: 45, name: "Hector", phone: "9493563186", ffg: "Chris Perez", age: "", coach: "Cesar Lopez", active: true, steps: {}, attendance: {} },
  { id: 46, name: "Leonel", phone: "213-448-7548", ffg: "Angel rodrigez", age: "", coach: "Cesar Lopez", active: true, steps: {}, attendance: {} },
  { id: 47, name: "Andrew Palacios", phone: "(562) 852-2432", ffg: "Mel Dylane", age: "37", coach: "Victor Lopez", active: true, steps: {}, attendance: {} },
  { id: 48, name: "Ezekiel Aleman", phone: "(323) 208-5684", ffg: "Carlos Tellez", age: "35", coach: "Victor Lopez", active: true, steps: {}, attendance: {} },
  { id: 49, name: "John Dominguez", phone: "(626) 941-7865", ffg: "Carlos Tellez", age: "42", coach: "Victor Lopez", active: true, steps: {}, attendance: {} },
  { id: 50, name: "Jose Pacheco", phone: "(213) 664-9519", ffg: "Bobby Arzola", age: "50", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 51, name: "David Pena", phone: "(562) 658-6502", ffg: "Will Biscardi", age: "46", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 52, name: "Zef Sandidge", phone: "(919) 822-4675", ffg: "Christian Luna", age: "46", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 53, name: "William Hemsley", phone: "(714) 631-3731", ffg: "Bobby Arzola", age: "46", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 54, name: "William Maciel", phone: "(562) 500-7903", ffg: "Will Biscardi", age: "", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 55, name: "Bobby Svay", phone: "(562) 708-2510", ffg: "isaac martinez", age: "", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 56, name: "Angel Caballero", phone: "(626) 491-7553", ffg: "Bobby Arzola", age: "20", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 57, name: "Billy Enriquez", phone: "9494398633", ffg: "ANGEL RODRIGUEZ", age: "", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 58, name: "Joseph Hunt", phone: "5623366241", ffg: "isaac martinez", age: "", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 59, name: "Matthew Morphin", phone: "(626) 491-8950", ffg: "CARLOS TELLEZ", age: "37", coach: "Bobby Arzola", active: true, steps: {}, attendance: {} },
  { id: 60, name: "Jakari Devore", phone: "(213) 854-3405", ffg: "Chris Perez", age: "20", coach: "Dominick Gonzalez / Davon", active: true, steps: {}, attendance: {} },
  { id: 61, name: "Fransisco Almeida", phone: "(714) 823-0115", ffg: "Will Biscardi", age: "26", coach: "Dominick Gonzalez / Davon", active: true, steps: {}, attendance: {} },
  { id: 62, name: "Kyle Slack", phone: "(310) 405-4248", ffg: "Will Biscardi", age: "32", coach: "Dominick Gonzalez / Davon", active: true, steps: {}, attendance: {} },
  { id: 63, name: "Zachary Townsend", phone: "2138082800", ffg: "Davon Livingston", age: "26", coach: "Dominick Gonzalez / Davon", active: true, steps: {}, attendance: {} },
  { id: 64, name: "Marco Torres", phone: "", ffg: "", age: "", coach: "Dominick Gonzalez / Davon", active: true, steps: {}, attendance: {} },
  { id: 65, name: "Joshua Contreras", phone: "6265581095", ffg: "angel rodrigez", age: "", coach: "Dominick Gonzalez / Davon", active: true, steps: {}, attendance: {} },
  { id: 66, name: "Anthony Gonsales", phone: "(626) 487-3899", ffg: "Dominick", age: "16", coach: "Dominick Gonzalez / Davon", active: true, steps: {}, attendance: {} },
  { id: 67, name: "Moses Krolczyk", phone: "3603608921", ffg: "Isaac Martinez", age: "24", coach: "Dominick Gonzalez / Davon", active: true, steps: {}, attendance: {} },
  { id: 68, name: "Vernon Abalos", phone: "3109785665", ffg: "Dominick Gonzalez", age: "39", coach: "Dominick Gonzalez / Davon", active: true, steps: {}, attendance: {} },
  { id: 69, name: "Xander Navarro", phone: "(562) 393-9072", ffg: "Oscar Corona", age: "", coach: "Justin Machado", active: true, steps: {}, attendance: {} },
  { id: 70, name: "Israel Romo", phone: "(323)239-5675", ffg: "Christian Luna", age: "", coach: "Justin Machado", active: true, steps: {}, attendance: {} },
  { id: 71, name: "Angel Marin", phone: "6264202132", ffg: "Angel Rodriguez", age: "", coach: "Justin Machado", active: true, steps: {}, attendance: {} },
  { id: 72, name: "Robert Perez", phone: "3233316022", ffg: "Christian Luna", age: "", coach: "Justin Machado", active: true, steps: {}, attendance: {} },
  { id: 73, name: "Rushane Campbell", phone: "8185882773", ffg: "Isaac Martinez", age: "30", coach: "Justin Machado", active: true, steps: {}, attendance: {} },
];

export const SEED_COACHES = [
  "Alex Gonzalez", "Alfred Appel", "Chris Perez",
  "Dylane Kamgang", "Evan Garcia", "Yony Bautista",
  "Cesar Lopez", "Victor Lopez", "Bobby Arzola",
  "Dominick Gonzalez / Davon", "Justin Machado",
];

export const DEFAULT_STAGES = ["Confirmation", "Encounter", "PIDS", "Prayer"];
